spring.jpa.properties.hibernate.dialec=org.hibernate.dialec.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:5432/bancocnab
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=auto
spring.jpa.show-sql=true

